[package]
name = "pod"
version = "0.0.0"
edition = "2024"

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[dependencies]
pod-macros = { path = "../pod-macros", version = "0.0.0" }

[dev-dependencies]
protocol = { path = "../protocol", version = "0.0.0" }
