[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
std = ["alloc", "pod/std"]
alloc = ["pod/alloc"]

[dependencies]
pod = { path = "../pod", default-features = false }
